name: Automated Test Cases

on: 
  push: 
    branches: 
      - 'master'
  pull_request: 
    branches: 
      - 'master'


jobs: 
  tests: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout job
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
            node-version: '20.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build --if-present    
      - name: Display Git Log Again
        run: |
          git log --pretty=format:" Branch: %d%x0A Commit: %H%x0A Author: %an <%ae>%x0A Date: %ad%x0A Message: %s%x0A" -n2
       